options {
    directory "/var/lib/bind";
    recursion yes;
    allow-recursion { any; };
    listen-on { any; };
    listen-on-v6 { any; };
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

zone "example.com" {
    type master;
    file "/etc/bind/zones/example.com.zone";
};
